[font]
size = 16
# 14.5

[font.normal]
family = "CMU Bright SemiBold" #"0xProto Nerd Font" #Terminus Liberation "Agave Nerd Font"
#style = "Regular"

[font.bold]
family = "CMU Sans Serif Bold" #"0xProto Nerd Font"
#style = "Bold"

[font.italic]
family = "CMU Typewriter Text" #"0xProto Nerd Font"
style = "Italic"

[font.bold_italic]
family = "CMU Typewriter Text"
style = "BoldItalic"

[window.padding]
x = 1
y = 1 

[window]
dynamic_padding = true
